packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  esbuild: true
  prisma: false
  unrs-resolver: true
  vue-demi: true
